name: Run junit tests

on:
  push:
    branches:
      - main
    paths:
      - 'src/**/model/**'
      - 'src/**/controller/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**/model/**'
      - 'src/**/controller/**'

jobs:
  build_and_test:
    concurrency:
        group: build_and_test
        cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Build and run unit tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: mvn test